# Example Apache HTTP server virtualhost configuration
# Includes support for TLS 1.0 for older ATAs/IP phones

# Bootstrap
<VirtualHost *:80>
	ServerName provision.example.com
	DocumentRoot /var/www/html/teleprovisioner
	<Directory /var/www/html/teleprovisioner>
		AllowOverride None
		Include /var/www/html/teleprovisioner/.htaccess
	</Directory>
	ErrorLog ${APACHE_LOG_DIR}/www_error.log
	CustomLog ${APACHE_LOG_DIR}/www_access.log combined
</VirtualHost>

# Grandstream
Listen 2443
<VirtualHost *:2443>
	ServerName provision.example.com
	DocumentRoot /var/www/html/teleprovisioner
	<Directory /var/www/html/teleprovisioner>
		SSLRequireSSL
		AllowOverride None
		Include /var/www/html/teleprovisioner/.htaccess
	</Directory>
	ErrorLog ${APACHE_LOG_DIR}/provision_error.log
	CustomLog ${APACHE_LOG_DIR}/provision_access.log combined
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/provision.crt
	SSLCertificateKeyFile /etc/ssl/private/provision.pem
	SSLCACertificateFile /etc/ssl/certs/grandstream-combined.crt
	SSLProtocol All
	SSLCipherSuite ALL:@SECLEVEL=0
	SSLOptions -StrictRequire +StdEnvVars
	SSLVerifyClient optional_no_ca
	SSLVerifyDepth 3
</VirtualHost>

# Polycom
Listen 2445
<VirtualHost *:2445>
	ServerName provision.example.com
	DocumentRoot /var/www/html/teleprovisioner
	<Directory /var/www/html/teleprovisioner>
		SSLRequireSSL
		AllowOverride None
		Include /var/www/html/teleprovisioner/.htaccess
	</Directory>
	ErrorLog ${APACHE_LOG_DIR}/provision_error.log
	CustomLog ${APACHE_LOG_DIR}/provision_access.log combined
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/provision.crt
	SSLCertificateKeyFile /etc/ssl/private/provision.pem
	SSLCACertificateFile /etc/ssl/certs/polycom_root_ca.crt
	SSLProtocol All
	SSLCipherSuite ALL:@SECLEVEL=0
	# +ExportCertData needed for $_SERVER['SSL_CLIENT_CERT']
	SSLOptions -StrictRequire +StdEnvVars +ExportCertData
	SSLVerifyClient optional_no_ca
	SSLVerifyDepth 3
</VirtualHost>
