<?php
header('Content-type: application/xml');
?>
<?xml version="1.0" standalone="yes"?>
<!-- Default Master SIP Configuration File-->
<!-- For information on configuring Polycom VoIP phones please refer to the -->
<!-- Configuration File Management white paper available from: -->
<!-- http://www.polycom.com/common/documents/whitepapers/configuration_file_management_on_soundpoint_ip_phones.pdf -->
<APPLICATION APP_FILE_PATH="sip.ld" DECT_FILE_PATH="3111-17823-001.dect.ld" CONFIG_FILES="" SERVICE_FILES="" MISC_FILES="" LOG_FILE_DIRECTORY="" OVERRIDES_DIRECTORY="" CONTACTS_DIRECTORY="" LICENSE_DIRECTORY="" USER_PROFILES_DIRECTORY="" CALL_LISTS_DIRECTORY="" COREFILE_DIRECTORY="" CERTIFICATE_DIRECTORY="" FLK_DIRECTORY="">
	
	<APPLICATION_SPIP300 CONFIG_FILES_SPIP300="polycom.cfg" />
	<APPLICATION_SPIP500 CONFIG_FILES_SPIP500="polycom.cfg" />
	<APPLICATION_SPIP301 CONFIG_FILES_SPIP301="polycom.cfg" />
	<APPLICATION_SPIP501 CONFIG_FILES_SPIP501="polycom.cfg" />
	<APPLICATION_SPIP600 CONFIG_FILES_SPIP600="polycom.cfg" />
	<APPLICATION_SPIP601 CONFIG_FILES_SPIP601="polycom.cfg" />
	<APPLICATION_SPIP430 CONFIG_FILES_SPIP430="polycom.cfg" />
	<APPLICATION_SPIP320 CONFIG_FILES_SPIP320="polycom.cfg" />
	<APPLICATION_SPIP330 CONFIG_FILES_SPIP330="polycom.cfg" />
	<APPLICATION_SPIP321 CONFIG_FILES_SPIP321="polycom.cfg" />
	<APPLICATION_SPIP331 APP_FILE_PATH_SPIP331="2345-12365-001.sip.ld" CONFIG_FILES_SPIP331="polycom.cfg" />
	<APPLICATION_SPIP335 CONFIG_FILES_SPIP335="polycom.cfg" />
	<APPLICATION_SPIP450 CONFIG_FILES_SPIP450="polycom.cfg" />
	<APPLICATION_SPIP550 CONFIG_FILES_SPIP550="polycom.cfg" />
	<APPLICATION_SPIP560 CONFIG_FILES_SPIP560="polycom.cfg" />
	<APPLICATION_SPIP650 CONFIG_FILES_SPIP650="polycom.cfg" />
	<APPLICATION_SPIP670 CONFIG_FILES_SPIP670="polycom.cfg" />
	<APPLICATION_SSIP4000 CONFIG_FILES_SSIP4000="polycom.cfg" />
	<APPLICATION_SSIP5000 CONFIG_FILES_SSIP5000="polycom.cfg" />
	<APPLICATION_SSIP6000 CONFIG_FILES_SSIP6000="polycom.cfg" />
	<APPLICATION_SSIP7000 CONFIG_FILES_SSIP7000="polycom.cfg" />
	<APPLICATION_SSDuo CONFIG_FILES_SSDuo="polycom.cfg" />
	<APPLICATION_VVX300 CONFIG_FILES_VVX300="polycom.cfg" />
	<APPLICATION_VVX310 CONFIG_FILES_VVX310="polycom.cfg" />
	<APPLICATION_VVX400 CONFIG_FILES_VVX400="polycom.cfg" />
	<APPLICATION_VVX400 CONFIG_FILES_VVX401="polycom.cfg" />
	<APPLICATION_VVX410 CONFIG_FILES_VVX410="polycom.cfg" />
	<APPLICATION_VVX411 CONFIG_FILES_VVX411="polycom.cfg" />
	<APPLICATION_VVX500 CONFIG_FILES_VVX500="polycom.cfg" />
	<APPLICATION_VVX600 CONFIG_FILES_VVX600="polycom.cfg" />
	<APPLICATION_VVX1500 CONFIG_FILES_VVX1500="polycom.cfg" />
</APPLICATION>
