<?php
header('Content-type: application/xml');
?>
<?xml version="1.0" standalone="yes"?>
<!-- Default Master SIP Configuration File-->
<!-- For information on configuring Polycom VoIP phones please refer to the -->
<!-- Configuration File Management white paper available from: -->
<!-- http://www.polycom.com/common/documents/whitepapers/configuration_file_management_on_soundpoint_ip_phones.pdf -->
<!-- e.g. <APPLICATION_SPIP300 APP_FILE_PATH_SPIP300="sip_213.ld" CONFIG_FILES_SPIP300="[PHONE_MAC_ADDRESS]-user.cfg" /> -->
<APPLICATION APP_FILE_PATH="sip.ld" DECT_FILE_PATH="3111-17823-001.dect.ld" CONFIG_FILES="" SERVICE_FILES="" MISC_FILES="" LOG_FILE_DIRECTORY="" OVERRIDES_DIRECTORY="" CONTACTS_DIRECTORY="" LICENSE_DIRECTORY="" USER_PROFILES_DIRECTORY="" CALL_LISTS_DIRECTORY="" COREFILE_DIRECTORY="" CERTIFICATE_DIRECTORY="" FLK_DIRECTORY="">
	<APPLICATION_SPIP300 CONFIG_FILES_SPIP300="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP500 CONFIG_FILES_SPIP500="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP301 CONFIG_FILES_SPIP301="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP501 CONFIG_FILES_SPIP501="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP600 CONFIG_FILES_SPIP600="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP601 CONFIG_FILES_SPIP601="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP430 CONFIG_FILES_SPIP430="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP320 CONFIG_FILES_SPIP320="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP330 CONFIG_FILES_SPIP330="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP321 CONFIG_FILES_SPIP321="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP331 CONFIG_FILES_SPIP331="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP335 CONFIG_FILES_SPIP335="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP450 CONFIG_FILES_SPIP450="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP550 CONFIG_FILES_SPIP550="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP560 CONFIG_FILES_SPIP560="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP650 CONFIG_FILES_SPIP650="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP670 CONFIG_FILES_SPIP670="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP4000 CONFIG_FILES_SSIP4000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP5000 CONFIG_FILES_SSIP5000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP6000 CONFIG_FILES_SSIP6000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP7000 CONFIG_FILES_SSIP7000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSDuo CONFIG_FILES_SSDuo="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX300 CONFIG_FILES_VVX300="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX310 CONFIG_FILES_VVX310="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX400 CONFIG_FILES_VVX400="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX401 CONFIG_FILES_VVX401="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX410 CONFIG_FILES_VVX410="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX411 CONFIG_FILES_VVX411="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX500 CONFIG_FILES_VVX500="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX600 CONFIG_FILES_VVX600="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX1500 CONFIG_FILES_VVX1500="[PHONE_MAC_ADDRESS]-user.cfg" />
	<!--
	<APPLICATION_SPIP300 APP_FILE_PATH_SPIP300="sip_213.ld" CONFIG_FILES_SPIP300="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP500 APP_FILE_PATH_SPIP500="sip_213.ld" CONFIG_FILES_SPIP500="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP301 APP_FILE_PATH_SPIP301="sip_318.ld" CONFIG_FILES_SPIP301="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP501 APP_FILE_PATH_SPIP501="sip_318.ld" CONFIG_FILES_SPIP501="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP600 APP_FILE_PATH_SPIP600="sip_318.ld" CONFIG_FILES_SPIP600="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP601 APP_FILE_PATH_SPIP601="sip_318.ld" CONFIG_FILES_SPIP601="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP430 APP_FILE_PATH_SPIP430="sip_327.ld" CONFIG_FILES_SPIP430="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP320 APP_FILE_PATH_SPIP320="sip_335.ld" CONFIG_FILES_SPIP320="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP330 APP_FILE_PATH_SPIP330="sip_335.ld" CONFIG_FILES_SPIP330="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP321 APP_FILE_PATH_SPIP321="sip_4014.ld" CONFIG_FILES_SPIP321="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP331 APP_FILE_PATH_SPIP331="sip_4014.ld" CONFIG_FILES_SPIP331="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP335 APP_FILE_PATH_SPIP335="sip_4014.ld" CONFIG_FILES_SPIP335="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP450 APP_FILE_PATH_SPIP450="sip_4014.ld" CONFIG_FILES_SPIP450="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP550 APP_FILE_PATH_SPIP550="sip_4014.ld" CONFIG_FILES_SPIP550="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP560 APP_FILE_PATH_SPIP560="sip_4014.ld" CONFIG_FILES_SPIP560="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP650 APP_FILE_PATH_SPIP650="sip_4014.ld" CONFIG_FILES_SPIP650="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SPIP670 APP_FILE_PATH_SPIP670="sip_4014.ld" CONFIG_FILES_SPIP670="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP4000 APP_FILE_PATH_SSIP4000="sip_318.ld" CONFIG_FILES_SSIP4000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP5000 APP_FILE_PATH_SSIP5000="sip_4014.ld" CONFIG_FILES_SSIP5000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP6000 APP_FILE_PATH_SSIP6000="sip_4014.ld" CONFIG_FILES_SSIP6000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSIP7000 APP_FILE_PATH_SSIP7000="sip_4014.ld" CONFIG_FILES_SSIP7000="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_SSDuo APP_FILE_PATH_SSDuo="sip_4014.ld" CONFIG_FILES_SSDuo="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX300 APP_FILE_PATH_VVX300="sip_590.ld" CONFIG_FILES_VVX300="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX310 APP_FILE_PATH_VVX310="sip_590.ld" CONFIG_FILES_VVX310="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX400 APP_FILE_PATH_VVX400="sip_590.ld" CONFIG_FILES_VVX400="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX410 APP_FILE_PATH_VVX410="sip_590.ld" CONFIG_FILES_VVX410="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX500 APP_FILE_PATH_VVX500="sip_590.ld" CONFIG_FILES_VVX500="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX600 APP_FILE_PATH_VVX600="sip_590.ld" CONFIG_FILES_VVX600="[PHONE_MAC_ADDRESS]-user.cfg" />
	<APPLICATION_VVX1500 APP_FILE_PATH_VVX1500="sip_590.ld" CONFIG_FILES_VVX1500="[PHONE_MAC_ADDRESS]-user.cfg" />
	-->
</APPLICATION>
